//
//  Werkvorm.m
//  Edufit
//
//  Created by richard kerkvliet on 16/06/14.
//  Copyright (c) 2014 richard kerkvliet. All rights reserved.
//

#import "Werkvorm.h"



@implementation Werkvorm

@synthesize WV_TC, WV_NR, WV_LT, WV_X1, WV_E, WV_R, WV_C, WV_T, WV_TCR, WV_TPR, WV_M, WV_GROEP, WV_BRON, WV_STER, WV_NAAM, WV_WWV, WV_X2, WV_GGMN, WV_GGMX, WV_V, WV_VMN, WV_VMX, WV_TY, WV_TMN, WV_TMX, WV_N, WV_NMN, WV_NMX, WV_LDC, WV_LDAANT, WV_DOEL01, WV_DOEL02, WV_DOEL03, WV_DOEL04, WV_DOEL05, WV_DOEL06, WV_DOEL07, WV_DOEL08, WV_DOEL09, WV_DOEL10, WV_DOEL11, WV_DOEL12, WV_DOEL13, WV_DOEL14, WV_DOEL15, WV_DOEL16, WV_DOEL17, WV_DOEL18, WV_DOEL19, WV_DOEL20, WV_DOEL21, WV_DOEL22, WV_DOEL23, WV_DOEL24, WV_DOEL25, WV_DOEL26, WV_DOEL27, WV_DOEL28, WV_DOEL29, WV_DOEL30, WV_DOEL31, WV_DOEL32, WV_NODIG, WV_UILG, WV_VTN, WV_VEN, WV_MITAL, WV_MI1VL, WV_MI2LM, WV_MI3VR, WV_MI4LK, WV_MI5MR, WV_MI6NA, WV_MI7IE, WV_MI8IA, WV_MEMO;

@end
